<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Job extends \App\Entities\Job implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'attempts' => [parent::class, 'attempts', null, 16],
        "\0".parent::class."\0".'availableAt' => [parent::class, 'availableAt', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'payload' => [parent::class, 'payload', null, 16],
        "\0".parent::class."\0".'queue' => [parent::class, 'queue', null, 16],
        "\0".parent::class."\0".'reservedAt' => [parent::class, 'reservedAt', null, 16],
        'attempts' => [parent::class, 'attempts', null, 16],
        'availableAt' => [parent::class, 'availableAt', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'payload' => [parent::class, 'payload', null, 16],
        'queue' => [parent::class, 'queue', null, 16],
        'reservedAt' => [parent::class, 'reservedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
