<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PersonalAccessToken extends \App\Entities\PersonalAccessToken implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abilities' => [parent::class, 'abilities', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'expiresAt' => [parent::class, 'expiresAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lastUsedAt' => [parent::class, 'lastUsedAt', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'token' => [parent::class, 'token', null, 16],
        "\0".parent::class."\0".'tokenable' => [parent::class, 'tokenable', null, 16],
        "\0".parent::class."\0".'tokenableType' => [parent::class, 'tokenableType', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'abilities' => [parent::class, 'abilities', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'expiresAt' => [parent::class, 'expiresAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lastUsedAt' => [parent::class, 'lastUsedAt', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'token' => [parent::class, 'token', null, 16],
        'tokenable' => [parent::class, 'tokenable', null, 16],
        'tokenableType' => [parent::class, 'tokenableType', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
