<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FailedJob extends \App\Entities\FailedJob implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'connection' => [parent::class, 'connection', null, 16],
        "\0".parent::class."\0".'exception' => [parent::class, 'exception', null, 16],
        "\0".parent::class."\0".'failedAt' => [parent::class, 'failedAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'payload' => [parent::class, 'payload', null, 16],
        "\0".parent::class."\0".'queue' => [parent::class, 'queue', null, 16],
        "\0".parent::class."\0".'uuid' => [parent::class, 'uuid', null, 16],
        'connection' => [parent::class, 'connection', null, 16],
        'exception' => [parent::class, 'exception', null, 16],
        'failedAt' => [parent::class, 'failedAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'payload' => [parent::class, 'payload', null, 16],
        'queue' => [parent::class, 'queue', null, 16],
        'uuid' => [parent::class, 'uuid', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
