<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JobBatch extends \App\Entities\JobBatch implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cancelledAt' => [parent::class, 'cancelledAt', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'failedJobIds' => [parent::class, 'failedJobIds', null, 16],
        "\0".parent::class."\0".'failedJobs' => [parent::class, 'failedJobs', null, 16],
        "\0".parent::class."\0".'finishedAt' => [parent::class, 'finishedAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'options' => [parent::class, 'options', null, 16],
        "\0".parent::class."\0".'pendingJobs' => [parent::class, 'pendingJobs', null, 16],
        "\0".parent::class."\0".'totalJobs' => [parent::class, 'totalJobs', null, 16],
        'cancelledAt' => [parent::class, 'cancelledAt', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'failedJobIds' => [parent::class, 'failedJobIds', null, 16],
        'failedJobs' => [parent::class, 'failedJobs', null, 16],
        'finishedAt' => [parent::class, 'finishedAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'options' => [parent::class, 'options', null, 16],
        'pendingJobs' => [parent::class, 'pendingJobs', null, 16],
        'totalJobs' => [parent::class, 'totalJobs', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
